version: 0.2

phases:
  install:
    commands:
      - echo Building app...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - bash -c "$(curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/master/install)"
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp --recursive build/ s3://$BUCKET_NAME/COMMIT/$CODEBUILD_RESOLVED_SOURCE_VERSION/ --acl=public-read
      - aws s3 cp --recursive build/ s3://$BUCKET_NAME/BRANCH/$BRANCH/ --acl=public-read
artifacts:
  files:
    - build/*
